export const DEFAULT_MAX_LIMIT = 500;
export const DEFAULT_LIMIT = 200;

export const DATASET_CATALOG = {
  sales: {
    view: "reporting.v_sales_fact",
    dateColumn: "created_date_peru",
    metrics: {
      net_sales: "COALESCE(SUM(total_amount), 0)::numeric(14,2)",
      orders: "COUNT(DISTINCT sale_id)",
      avg_ticket: "COALESCE(AVG(total_amount), 0)::numeric(14,2)",
      distinct_customers: "COUNT(DISTINCT customer_id)",
    },
    dimensions: {
      day: "created_date_peru",
      store_id: "store_id",
      store_name: "store_name",
      seller_id: "seller_id",
      seller_name: "seller_name",
      status: "status",
      document_type: "document_type",
    },
    filters: {
      store_id: "store_id",
      seller_id: "seller_id",
      status: "status",
      customer_id: "customer_id",
    },
  },
  sale_items: {
    view: "reporting.v_sale_items_fact",
    dateColumn: "sale_created_date_peru",
    metrics: {
      items_sold: "COALESCE(SUM(quantity), 0)",
      item_revenue: "COALESCE(SUM(total_price), 0)::numeric(14,2)",
      distinct_products: "COUNT(DISTINCT product_id)",
      distinct_sales: "COUNT(DISTINCT sale_id)",
    },
    dimensions: {
      day: "sale_created_date_peru",
      store_id: "store_id",
      store_name: "store_name",
      product_id: "product_id",
      product_name: "product_name",
      product_type: "product_type",
      location_bin: "location_bin",
      seller_id: "seller_id",
      seller_name: "seller_name",
    },
    filters: {
      store_id: "store_id",
      product_id: "product_id",
      product_type: "product_type",
      location_bin: "location_bin",
      seller_id: "seller_id",
      customer_id: "customer_id",
    },
  },
  payments: {
    view: "reporting.v_payments_fact",
    dateColumn: "payment_date_peru_date",
    metrics: {
      payments_total: "COALESCE(SUM(amount), 0)::numeric(14,2)",
      payments_count: "COUNT(*)",
      avg_payment: "COALESCE(AVG(amount), 0)::numeric(14,2)",
      distinct_sales: "COUNT(DISTINCT sale_id)",
    },
    dimensions: {
      day: "payment_date_peru_date",
      payment_method: "payment_method",
      payment_method_label: "payment_method_label",
      sale_store_id: "sale_store_id",
      payment_store_id: "payment_store_id",
      sale_store_name: "sale_store_name",
      payment_store_name: "payment_store_name",
      seller_id: "seller_id",
      seller_name: "seller_name",
    },
    filters: {
      payment_method: "payment_method",
      payment_store_id: "payment_store_id",
      sale_store_id: "sale_store_id",
      seller_id: "seller_id",
      customer_id: "customer_id",
    },
  },
  inventory: {
    view: "reporting.v_inventory_snapshot",
    dateColumn: "date(balance_updated_at_peru)",
    metrics: {
      on_hand_qty: "COALESCE(SUM(on_hand), 0)",
      reserved_qty: "COALESCE(SUM(reserved), 0)",
      available_qty: "COALESCE(SUM(available_qty), 0)",
      stock_value: "COALESCE(SUM(available_stock_value), 0)::numeric(14,2)",
      sku_count: "COUNT(DISTINCT product_id)",
    },
    dimensions: {
      day: "date(balance_updated_at_peru)",
      store_id: "store_id",
      store_name: "store_name",
      store_type: "store_type",
      product_type: "product_type",
      product_status: "product_status",
      location_bin: "location_bin",
    },
    filters: {
      store_id: "store_id",
      store_type: "store_type",
      product_type: "product_type",
      product_status: "product_status",
      location_bin: "location_bin",
    },
  },
  sales_operations: {
    view: "reporting.v_sales_operations_detail",
    dateColumn: "created_date_peru",
    metrics: {
      item_total: "COALESCE(SUM(item_total_amount), 0)::numeric(14,2)",
      lines_count: "COUNT(DISTINCT sale_item_id)",
      sales_count: "COUNT(DISTINCT sale_id)",
    },
    dimensions: {
      sale_id: "sale_id",
      day: "created_date_peru",
      time: "created_time_peru",
      customer_id: "customer_id",
      customer_name: "customer_name",
      customer_doc_type: "customer_doc_type",
      customer_doc_number: "customer_doc_number",
      seller_id: "seller_id",
      seller_name: "seller_name",
      store_id: "store_id",
      store_name: "store_name",
      product_id: "product_id",
      product_name: "product_name",
      product_type: "product_type",
      quantity: "quantity",
      unit_price: "unit_price",
      item_total_amount: "item_total_amount",
      sale_total_amount: "sale_total_amount",
      captured_imei: "captured_imei",
      captured_serial: "captured_serial",
      lookup_code: "lookup_code",
      payment_methods: "payment_methods",
    },
    filters: {
      sale_id: "sale_id",
      customer_id: "customer_id",
      customer_doc_number: "customer_doc_number",
      captured_imei: "captured_imei",
      captured_serial: "captured_serial",
      lookup_code: "lookup_code",
      seller_id: "seller_id",
      store_id: "store_id",
      product_id: "product_id",
      product_type: "product_type",
    },
  },
};

export const DATASET_KEYS = Object.keys(DATASET_CATALOG);
